global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

# TODO: Service discovery prom
scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'docker.for.mac.localhost:9992'
          - 'docker.for.mac.localhost:1415'
