environment: "development"
server:
  version: 0
  address: ":5044"
  resilience:
    rate_limiter:
      limit: 1000
      iplimit: 100
    circuit_breaker:
      timeout: 2500
  cors:
    origins: ["https://backend", "https://frontend"]
onlyoffice:
  doc_secret: "onlyoffice_document_secret"
  max_size: 2100000 #MBs
repl:
  version: 0
  address: ":3132"
  debug: true
broker:
  type: 2
  addresses: [""]
registry:
  addresses: [""]
  type: 2
tracer:
  enable: true
  address: "http://zipkin/api/v2/spans"
  type: 1
worker:
  address: "redis_address (0.0.0.0:6379)"
  namespace: "onlyoffice-callback"
logger:
  name: "callback.logger"
  level: 1
  color: true
