version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.3.3
    container_name: elasticsearch
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
  logstash:
    image: logstash:8.3.3
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
  filebeat:
    image: elastic/filebeat:8.3.3
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $LOGS_PATH:/logs/
  kibana:
    image: kibana:8.3.3
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601
