environment: "development"
server:
  version: 0
  address: ":5051"
  resilience:
    rate_limiter:
      limit: 500
zoom:
  client_id: "zoom_client_id"
  client_secret: "zoom_client_secret"
persistence:
  url: "mongodb://host:port"
repl:
  version: 0
  address: ":8989"
  debug: true
broker:
  type: 2
  addresses: [""]
registry:
  addresses: [""]
  type: 2
tracer:
  enable: true
  address: "http://zipkin/api/v2/spans"
  type: 1
logger:
  name: "auth-logger"
  level: 1
  color: true
